version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'container-registry.oracle.com/oracle_linux_automation_manager/olam-ee:latest'
dependencies:
  #galaxy: requirements.yml
  #python: requirements.txt
  system: bindep.txt
#ansible_config: 'ansible.cfg'
additional_build_steps:
  prepend:
    #- RUN pip3 install --upgrade pip setuptools
    - RUN pip3 install --upgrade pip setuptools 
    - RUN pip3 install oci
    - RUN pip3 install ansible
    - RUN ansible-galaxy collection install -f oracle.oci
#  append:
#    - RUN pip3 list installed

